package com.gykj.zhumulangma.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gykj.zhumulangma.common.bean.PlayHistoryBean;
import com.gykj.zhumulangma.common.bean.SearchHistoryBean;
import com.gykj.zhumulangma.common.bean.LikeBean;
import com.gykj.zhumulangma.common.bean.SubscribeBean;

import com.gykj.zhumulangma.common.dao.PlayHistoryBeanDao;
import com.gykj.zhumulangma.common.dao.SearchHistoryBeanDao;
import com.gykj.zhumulangma.common.dao.LikeBeanDao;
import com.gykj.zhumulangma.common.dao.SubscribeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playHistoryBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig likeBeanDaoConfig;
    private final DaoConfig subscribeBeanDaoConfig;

    private final PlayHistoryBeanDao playHistoryBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final LikeBeanDao likeBeanDao;
    private final SubscribeBeanDao subscribeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playHistoryBeanDaoConfig = daoConfigMap.get(PlayHistoryBeanDao.class).clone();
        playHistoryBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        subscribeBeanDaoConfig = daoConfigMap.get(SubscribeBeanDao.class).clone();
        subscribeBeanDaoConfig.initIdentityScope(type);

        playHistoryBeanDao = new PlayHistoryBeanDao(playHistoryBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);
        subscribeBeanDao = new SubscribeBeanDao(subscribeBeanDaoConfig, this);

        registerDao(PlayHistoryBean.class, playHistoryBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(LikeBean.class, likeBeanDao);
        registerDao(SubscribeBean.class, subscribeBeanDao);
    }
    
    public void clear() {
        playHistoryBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
        likeBeanDaoConfig.clearIdentityScope();
        subscribeBeanDaoConfig.clearIdentityScope();
    }

    public PlayHistoryBeanDao getPlayHistoryBeanDao() {
        return playHistoryBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

    public SubscribeBeanDao getSubscribeBeanDao() {
        return subscribeBeanDao;
    }

}
