package com.gykj.zhumulangma.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gykj.zhumulangma.common.bean.PlayHistoryBean;
import com.gykj.zhumulangma.common.bean.SearchHistoryBean;
import com.gykj.zhumulangma.common.bean.TrackDownloadBean;

import com.gykj.zhumulangma.common.dao.PlayHistoryBeanDao;
import com.gykj.zhumulangma.common.dao.SearchHistoryBeanDao;
import com.gykj.zhumulangma.common.dao.TrackDownloadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playHistoryBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig trackDownloadBeanDaoConfig;

    private final PlayHistoryBeanDao playHistoryBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final TrackDownloadBeanDao trackDownloadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playHistoryBeanDaoConfig = daoConfigMap.get(PlayHistoryBeanDao.class).clone();
        playHistoryBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        trackDownloadBeanDaoConfig = daoConfigMap.get(TrackDownloadBeanDao.class).clone();
        trackDownloadBeanDaoConfig.initIdentityScope(type);

        playHistoryBeanDao = new PlayHistoryBeanDao(playHistoryBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        trackDownloadBeanDao = new TrackDownloadBeanDao(trackDownloadBeanDaoConfig, this);

        registerDao(PlayHistoryBean.class, playHistoryBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(TrackDownloadBean.class, trackDownloadBeanDao);
    }
    
    public void clear() {
        playHistoryBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
        trackDownloadBeanDaoConfig.clearIdentityScope();
    }

    public PlayHistoryBeanDao getPlayHistoryBeanDao() {
        return playHistoryBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public TrackDownloadBeanDao getTrackDownloadBeanDao() {
        return trackDownloadBeanDao;
    }

}
